version: '3.8' # Or remove this line if you did earlier

services:
  mongodb:
    # ... (mongodb service definition remains the same) ...
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  python_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: python_etl_app
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./data:/usr/src/app/data
      - ./app:/usr/src/app
    command: python etl_script.py # <--- SIMPLIFIED COMMAND

volumes:
  mongo_data: